'use client'

import { Database } from '../../types/supabase'

type WeightNote = Database['public']['Tables']['weight_notes']['Row']

interface WeightNotePrintPreviewProps {
  weightNote: WeightNote
  onPrint: () => void
  onBack: () => void
}

export function WeightNotePrintPreview({ weightNote, onPrint, onBack }: WeightNotePrintPreviewProps) {
  const handlePrint = () => {
    window.print()
    onPrint()
  }

  return (
    <div className="space-y-6">
      {/* Print Actions */}
      <div className="flex justify-between items-center no-print">
        <button
          onClick={onBack}
          className="px-4 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-50"
        >
          Back to List
        </button>
        <button
          onClick={handlePrint}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          Print Weight Note
        </button>
      </div>

      {/* Printable Content */}
      <div className="bg-white p-8 shadow-lg print:shadow-none">
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold">ClamFlow Weight Note</h1>
          <p className="text-gray-600">Quality Control Documentation</p>
        </div>

        <div className="grid grid-cols-2 gap-8 mb-8">
          <div>
            <h3 className="font-semibold mb-4">Weight Note Details</h3>
            <div className="space-y-2">
              <div><strong>Box Number:</strong> {weightNote.box_number}</div>
              <div><strong>Weight:</strong> {weightNote.weight} kg</div>
              <div><strong>Created:</strong> {new Date(weightNote.created_at || '').toLocaleDateString()}</div>
              <div><strong>Status:</strong> {weightNote.workflow_completed ? 'Completed' : 'In Progress'}</div>
            </div>
          </div>
          
          <div>
            <h3 className="font-semibold mb-4">Authentication Details</h3>
            <div className="space-y-2">
              <div><strong>Current Step:</strong> {weightNote.authentication_step}/4</div>
              <div><strong>Production Auth:</strong> {weightNote.production_auth_method || 'Not completed'}</div>
              <div><strong>Supplier Auth:</strong> {weightNote.supplier_auth_method || 'Not completed'}</div>
              <div><strong>QC Status:</strong> {weightNote.qc_approval_status}</div>
            </div>
          </div>
        </div>

        <div className="border-t pt-8">
          <div className="text-center text-sm text-gray-600">
            <p>This document was generated by the ClamFlow Quality Management System</p>
            <p>Generated on: {new Date().toLocaleString()}</p>
          </div>
        </div>
      </div>

      <style jsx>{`
        @media print {
          .no-print {
            display: none !important;
          }
        }
      `}</style>
    </div>
  )
}

export default WeightNotePrintPreview